### ISSUE TITLE
Packaging 'jscs' doesn't work

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#5] opened 2016-02-02 18:02 UTC
If you try to pack jscs with nova then you get:

<pre>
1:jscs
/usr/share/nova/history.rb:39:in `last': undefined method `-' for nil:NilClass (NoMethodError)
    from /usr/share/nova/dependencies.rb:49:in `block (2 levels) in list'
    from /usr/share/nova/dependencies.rb:44:in `each'
    from /usr/share/nova/dependencies.rb:44:in `block in list'
    from /usr/share/nova/dependencies.rb:43:in `each'
    from /usr/share/nova/dependencies.rb:43:in `list'
    from /usr/share/nova/dependencies.rb:91:in `block in list'
    from /usr/share/nova/dependencies.rb:87:in `each'
    from /usr/share/nova/dependencies.rb:87:in `list'
    from /usr/share/nova/dependencies.rb:122:in `write'
    from /usr/bin/nova:12:in `<main>'
</pre>

**Comment by marguerite** [comment] 2016-02-03 05:39
commit [7a09060](https://github.com/marguerite/nodejs-packaging/commit/7a090608ed44209fc0a2cff34ff7f190bd677331) fixed the history.rb error. but there're still other errors related with jscs packaging.

**Comment by illuusio** [comment] 2016-02-03 06:56
Node.js package.json is too flexible that it's making it little bit brain-dead. They should only allow one way to express decencies and that's it.
I think jscs eats 1/4 my repo packages so if this could be installed then anything will.

**Comment by marguerite** [comment] 2016-02-03 07:16
yes, big challenge for me too. nova loops 36000 times and fails on jscs...a bit hard to debug 😅

**Comment by illuusio** [comment] 2016-02-03 07:28
Have you found which package fails?

**Comment by illuusio** [comment] 2016-02-03 11:05
As I'm looking it now. It should cache Version's or whole JSON comes from npmjs.org. That is how don't have to do 30k downloads. Because it seem it's >50% same packages that is fetched from npmjs.org.

**Comment by marguerite** [comment] 2016-02-03 11:11
@illuusio I add `p <variable name>` at some important place, then I can tell which part is wrong according to the output

**Comment by marguerite** [comment] 2016-02-03 11:13
@illuusio and delete them all after the generation of `<name>.json` file? looks good.

**Comment by illuusio** [comment] 2016-02-03 11:37
Hmm.. now I can't understand what you want me to do?

**Comment by marguerite** [comment] 2016-02-03 12:11
U don't need to do anything:-)

**Comment by marguerite** [comment] 2016-02-03 16:54
it seems `jscs` caused some exception beyond my parent finding logic, that keeps writing `babel-runtime` and `core-js` dependencies everywhere endlessly.

the logic itself is good. I tried it on `azure` module this evening, the main `package.json` requires 32 dependencies, more than 28 of `jscs`.

will write down the dependency tree tomorrow and process it by my brain on my code to debug what happened.

**Comment by marguerite** [comment] 2016-02-03 17:19
by the way, if you want to clean the unneeded dependencies (because now bundled in eg, jshint, the nodejs-\* dependency packages are useless then) in your repository some day, like what I did for npm and azure in devel:languages:nodejs, here's how:

copy scripts/batch-delete.rb and json2txt.rb to your local directory of the repo.

modify the locations and repository I hard coded in the scripts.

copy eg, jshint.json to the same directory of the two scripts.

run json2txt.rb, a packages.txt will be generated with all packages that are dependencies of jshint and exist in your repository.

run batch-delete.rb. will:

delete the binaries from download.opensuse.org;
drop the package from build.opensuse.org ;
delete the package directory on your local machine;
keep your repo config (.osc/_packages) clean and free of these gone packages 

:-)

I may publish them as node-migration-batch-delete and node-migration-json2pkgtxt in next beta release

**Comment by marguerite** [comment] 2016-02-03 19:21
@illuusio 

I can confirm this is not my problem, see this simplest dependency map I draw:

<pre>
{jscs:{
    babel-jscs:{
        babel-traverse:{
            babel-types:{
                babel-traverse:{}
            }
        }
    }
 }
}
</pre>

babel-traverse requires babel-types, then babel-types requires babel-traverse again.

bang! endless loop is created by upstream!

please tell the developer of babel-types.

**Comment by marguerite** [comment] 2016-02-03 19:24
it's apparent that I can't do anything from my side.

wait, I can add a check to drop babel-traverse dependency for babel-types in this case. (that is, child can't have parent as dependency)

but then babel-traverse will break

**Comment by marguerite** [comment] 2016-02-03 19:31
https://github.com/babel/babel/commit/e152e7044e469548f1260487ac83e1e0195bcf3f

that project didn't enable issue tracker, I added a line note for its developers

**Comment by marguerite** [comment] 2016-02-04 01:05
try again if I can do something from my side to resolve the endless loop

**Comment by marguerite** [comment] 2016-02-04 01:18
npm find dependencies from inner to outside, so I think drop babel-traverse for babel-types will not break anything.

**Comment by marguerite** [comment] 2016-02-04 06:03
@illuusio now the endless loop problem is solved by me. but another `f**k` issue comes out:

argparse requires lodash in this way '>= 4.0.0 < 5.0.0'.

Technically this means '>=0.0.0 && =4.0.0 && <0.0.0 && =5.0.0', which is definitely null.

need to workaround this. sigh...

**Comment by marguerite** [comment] 2016-02-04 06:21
fixed in trunk

**Closed as completed by marguerite** 2016-02-04 06:21 UTC

**Comment by illuusio** [comment] 2016-02-04 06:29
I start migrating my packages to new scheme now all my needed tools works. Only thing that I'm wondering are they named after nodejs-somename or nodejs-somename-prebuild (which your take) or nodejs-somename-bundle. I think that should be said loud and clean somehow in nodejs-packaging and check if naming really follow that.

**Comment by marguerite** [comment] 2016-02-04 09:17
@illuusio 

well there're a few features I want to achieve first. then I'll post on the mailing list to discuss the new naming scheme for the bundle.

**Comment by marguerite** [comment] 2016-02-04 09:19
and phantomjs`-prebuilt` is not the name I chose, but the upstream name is called `phantomjs-prebuilt`

**Comment by illuusio** [comment] 2016-02-04 10:28
Which mailing list this nodejs things are discussed?

**Comment by marguerite** [comment] 2016-02-04 10:42
@illuusio usually we discuss packaging related things on opensuse-packaging@opensuse.org
